name: Build and Release

on:
  # pull_request:
  #   branches:
  #     - main
  push:
    branches:
      - feature/use-mui
    tags:
      - 'v*.*.*' # Triggers the workflow on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.10.0' # Specify the Node.js version you need
      - name: Check Node Version
        run: node -v

      - name: Install pnpm
        run: npm install -g pnpm@latest

      - name: Install dependencies
        run: pnpm install

      - name: Build the project
        run: pnpm build

      - name: Upload dist.zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/feature/use-mui'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          pattern: dist*
          path: ./release

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Get current branch
        id: get_branch
        run: echo "::set-output name=branch::$(git rev-parse --abbrev-ref HEAD)"

      - name: Create tag
        id: create_tag
        run: |
          TAG_NAME="release-$(date +'%Y%m%d%H%M%S')-${{ steps.get_branch.outputs.branch }}"
          echo "::set-output name=tag_name::$TAG_NAME"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.CANDY_SUITE_WORKFLOW_GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.tag_name }}
          release_name: ${{ steps.create_tag.outputs.tag_name }}
          prerelease: true
          body: 'Release for ${{ steps.create_tag.outputs.tag_name }}'

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.CANDY_SUITE_WORKFLOW_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/dist.zip
          asset_name: dist.zip
          asset_content_type: application/zip
